version: "3.8"

volumes:
  mariadb_vol: {}
  wordpress_vol: {}

services:
  db:
    image: mariadb
    volumes:
      - mariadb_vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: senharootwordpress
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: senhawordpress

  blog:
    image: wordpress
    volumes:
      - wordpress_vol:/var/www/html
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: senhawordpress
      WORDPRESS_DB_NAME: wordpress